### ISSUE TITLE
Weird light bug.

### ISSUE THREAD

**Issue by RDKRACZ** [magistermaks/mod-fading#1]
Look at the light levels
![image](https://user-images.githubusercontent.com/43277609/110477582-a0e18d80-80e3-11eb-81f0-57d38203c12c.png)
![image](https://user-images.githubusercontent.com/43277609/110477618-accd4f80-80e3-11eb-9f9f-a3ec9c84428d.png)
![image](https://user-images.githubusercontent.com/43277609/110477863-f9b12600-80e3-11eb-992b-c4ce917f9ede.png)

**Comment by RDKRACZ** [comment]
![image](https://user-images.githubusercontent.com/43277609/110478128-4e54a100-80e4-11eb-89f9-74823df3d1d3.png)
can't destoy this

**Comment by RDKRACZ** [comment]
I'm not sure if this is caused by Fading - I remember I had some items from Botania placed here and I removed Botania without destroying these items.

**Comment by magistermaks** [comment]
Yeah, that's not fading's issue, removing blocks causes lighting glitches
