### ISSUE TITLE
Fading.properties Settings don't work | Or am I just dumb?

### ISSUE THREAD

**Issue by Toilet-Man** [magistermaks/mod-fading#10]
Hello, I found that the default settings were very annoying so I wanted to change them. I went to your Github help page for the mod and found it **VERY confusing** (I'm sure you thought it made sense at the time of writing it and I don't blame you). 

I tried the method I found the most instinctive: **_setting.name = * number *_**.

_I might just be dumb but I think an example would be much needed in **[Help.md](https://github.com/magistermaks/mod-fading/blob/master/HELP.md)**_

Here's what settings I changed to find out if the properties really worked:
```
time.campfire.max=6500
time.campfire.min=4100

time.torch.min=3000
time.torch.max=4500
time.lantern.min=3000
time.lantern.max=4500


rain.campfire=4000
rain.torch=1000
rain.lantern=9999
```

Something tells me it should be 

**_setting.name, * number *_** but to me, it doesn't make sense.

**Comment by magistermaks** [comment]
Yeah it's a little technical :P 
`setting.name=number` (no spaces) is the correct way to do this
you can always see the settings file generated by the mod on startup for reference (`config/fading.properties`)
btw are you sure that 4100-6500 is the time you want? :thinking: it's like 4 irl days (the time ranges are in minutes)

**Comment by Toilet-Man** [comment]
> `setting.name=number` (no spaces) is the correct way to do this
Thanks a lot <3
I would recommend writing an example of a setting on your [help page](https://github.com/magistermaks/mod-fading/blob/master/HELP.md)!


> you can always see the settings file generated by the mod on startup for reference (`config/fading.properties`)
Reference? The only thing written in fading.properties is
```
# Configuration file for mod Fading, intended for modpack makers and advanced users!
# Generated on Fri Aug 06 17:19:38 EDT 2021
# See: https://github.com/magistermaks/mod-fading/blob/master/HELP.md

```

> it's like 4 irl days (the time ranges are in minutes)
No, don't worry it was just a test so I would be sure they don't go out on the same day while I was testing the settings

**Comment by magistermaks** [comment]
> Reference? The only thing written in fading.properties (until I write something) is:  

oh yeah, my bad :P
> I would recommend writing an example of a setting on your  

fixed, thanks for feedback!
