### ISSUE TITLE
Improve the config file.

### ISSUE THREAD

**Issue by RDKRACZ** [magistermaks/mod-fading#3]
I can't understand how to change things because it is empty instead of the default values.
e.g.

-
![image](https://user-images.githubusercontent.com/43277609/110479477-bbb50180-80e5-11eb-91ef-7d1ddcdca69b.png)

so like
`other.disintegrate=true`?

-
![image](https://user-images.githubusercontent.com/43277609/110479625-e737ec00-80e5-11eb-8f66-9e2d01197d81.png)
rain.torch=what? I would like it to be set like rain will always extinguish a torch but after a random time between 5-20 seconds. Is this possible?

**Comment by magistermaks** [comment]
> so like
> other.disintegrate=true?  

yes,

> rain.torch=what?  

the description of the rain config option is a little limited i agree, but i tells that it supposed to be an integer value so:
`rain.torch=2` (that's the default value)

> I would like it to be set like rain will always extinguish a torch but after a random time between 5-20 seconds. Is this possible?

No, the best you can do is set it to 1, that would make rain burnout two times more common than default.
setting it to an exact time is impossible. bc rain burnout is not time but random tick based, so with random tick set to the default value of 3 and rain.torch to 1 it would take about 1 minute (on average)

**Comment by magistermaks** [comment]
> it is empty instead of the default values.

i left the config empty so that when i decide to tweak the default values users don't have to delete their config files in order for the changes to be applied

**Comment by RDKRACZ** [comment]
Thanks, it's working. I would like you to add one small feature if possible - I'm playing with 'other.disintegrate=true' so my torches disappear after burning out but they disappear when extinguished by the rain too. I would like them to become unlit when it's raining.

**Comment by magistermaks** [comment]
Ok, sorry for taking so long to upload this but i completely forgot about it, anyway 1.2.2 is now on curseforge
