### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by NokioPaul** [magistermaks/mod-fading#4]
![unknown (19)](https://user-images.githubusercontent.com/66056888/111907437-92856100-8a55-11eb-8c10-aeb4c9a87730.png)

**Comment by Misiek5535** [comment]
Server side crash only(at least for me). It also crashes on ... .playTorchSmoke... so torches placed on walls and ground cause problems. Until I placed any torches there were no problems. Pls fix asap as that is only thing that is holding me back from hosting a server with this mod.

**Comment by magistermaks** [comment]
This commit 490e1bdad167bb3e7e1848de122b385448ecc685 should fix it, but i still need to test it. i will publish a new version to cf later today if no problems are found

**Comment by magistermaks** [comment]
The updated version is now on curseforge
